### ISSUE TITLE
HTML to PDF conversion with API drops the "start" attribute from <ol> tags

### ISSUE THREAD

**Issue by jakemwp** [Docverter/docverter#42]
Ran into a problem where the above happens. Here is what I expect it to look like (ignore the extra nonsense- going to this page also echos out the response from running the docverter CURL request)

http://67.227.192.13/~hosttestmyphpski/html_to_pdf/html_templates/capital-dental-purchase-agreement.php

And here is a PDF generated by that HTML:http://67.227.192.13/~hosttestmyphpski/html_to_pdf/html_templates/TestContact12342014.pdf

Notice that the ordered lists start 1 and end at 9 for the HTML but in the PDF they reset every everytime there is new list instead counting up for each option. 

Any idea on what could be causing this?

**Comment by jakemwp** [comment]
Any response on why my start attribute is dropped from the PDF and each list starts from 1?

**Comment by jakemwp** [comment]
I've tried adding the "value" tag to the list elements themselves, but even those get dropped.

What it ends up looking like: https://jsfiddle.net/a21oppv0/

Expected result: https://jsfiddle.net/cfrqjv0o/2/

Same thing happens either way the list always starts at the beginning. Going to try making new classes in CSS and setting it that way next.

**Comment by peterkeen** [comment]
No idea, sorry. It could be a flyingsaucer bug (that's the thing that does
HTML -> PDF) but the version of flyingsaucer we use is very old, and
there's no upgrade path.

**Comment by jakemwp** [comment]
Figured it out- just had to use CSS instead. This works like a charm: https://jsfiddle.net/a21oppv0/1/

**Comment by peterkeen** [comment]
Great! Thanks for the update.
