### ISSUE TITLE
Please add a 'This project is no-longer supported line'

### ISSUE THREAD

**Issue by unsalted** [Docverter/docverter#44]
It's pretty clear after reading through the issues that the heroku deploy is broken.  It may be a good idea to make it clear that the project is no longer supported so that we don't waste time deploying and debugging issues on an unsupported app.

**Comment by peterkeen** [comment]
It's not that the project is unsupported. I just don't deploy it to Heroku so I haven't taken the time to figure it out.

Maybe try and ask the question next time instead of presuming to know the answer.

**Comment by unsalted** [comment]
It's a great setup and I like what you put together but... It's not a presumption: there are multiple pull requests with fixes to this problem.  I will add a new (not fully tested) pull request in a moment that combines those fixes.  But not working after a year and multiple issues reported is the definition of unsupported.  Well at-least an unsupported feature which should be documented as such. Documentation prevents me from needing to go down a rabbit hole and spend more time than I set aside for this particular problem.

**Comment by unsalted** [comment]
#45 <--- this got things up and running in a single push - I have only tested a md to pdf conversion so far.
