### ISSUE TITLE
Using multiple images to convert in a document

### ISSUE THREAD

**Issue by wisejoy7** [Docverter/docverter#54]
Hi,

I was trying to convert a html to pdf document. To make this conversion I use your api using PHP. I do this by using **'other_files[]' => "@/".realpath('example_files/images.jpg'),** and the file conversion is success but I want to convert html to pdf with multiple images in it. How do I assign multiple images in **other files[]** variable. I tried using **array("@/".realpath('example_files/images.jpg'), "@/".realpath('example_files/images.jpg'))** but that did not work.

```
<?php

$filename = $_GET['filesx'];

//set POST variables
$url = 'http://c.docverter.com/convert';
$fields = array('from' => 'html',
	'to' => 'pdf',
	'input_files[]' => "@/".realpath('example_files/'.$filename).";type=text/html; charset=UTF-8",
	'other_files[]' => "@/".realpath('example_files/images.jpg'),
);
 
$ch = curl_init(); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: multipart/form-data"));
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POSTFIELDS, $fields); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$result = curl_exec($ch);
curl_close($ch);
 
$finalx = strstr($filename , '.html', true);

$fp = fopen('uploads/'.$finalx.'.pdf', 'w');
fwrite($fp, $result);
fclose($fp);
 
echo '<script type="text/javascript">
           window.location = "http://docs.google.com/viewer?url=reviewitapp.co/docvert/doc/examples/php/uploads/'.$finalx.'.pdf&embedded=true"
      </script>'; 
```

**Comment by wisejoy7** [comment]
Can you please let me know the solution. I tried many things from array as mentioned above, separated file paths by comma and also tried re writing the same statement with different file path. Nothing works for me. :(

**Comment by wisejoy7** [comment]
I need this issue fixed soon brother. Please help me. :(

**Comment by peterkeen** [comment]
I don't know PHP. You should look into how to assign multiple values to the
same param name in the curl docs.
