### ISSUE TITLE
API Down?

### ISSUE THREAD

**Issue by jakemwp** [Docverter/docverter#55]
So the API end point is always returning false, and I can't access the web page for docverter anymore. Is the API ever going to come back, or do I need to go to the local SDK?

**Comment by peterkeen** [comment]
It should be back in about 24 hours. I moved some DNS stuff around and deleted something before I should have.

**Comment by jakemwp** [comment]
Thanks for the quick reply. I'm going to work on getting the local install on my server up and running since I need to use it today. Thank you for making that available.

**Comment by jakemwp** [comment]
Any updates on this?

**Comment by peterkeen** [comment]
Hm. Try clearing the DNS cache on your machine. I wonder if something is
aggressively caching something. I changed DNS servers and didn't wait the
full TTL before deleting the old ones.

**Comment by jakemwp** [comment]
Tried flushing my DNS on local and server. Still coming up empty. Even tried isitdownorjust.me and it says site is currently down for https://www.docverter.com/ and c.docverter.com/convert as well.

**Comment by peterkeen** [comment]
Augh. Sorry. Should be fixed now. If it still doesn't work try clearing the
cache again. I messed up way more than I thought I had :(

**Comment by jakemwp** [comment]
Got on my laptop, trying server now.

**Comment by jakemwp** [comment]
We are all set. Thanks dude.
